/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated.dashboard.index'
import { Route as AuthenticatedDashboardHistoryRouteImport } from './routes/_authenticated.dashboard.history'
import { Route as AuthenticatedDashboardJobsRouteImport } from './routes/_authenticated.dashboard.jobs'
import { Route as AuthenticatedDashboardPricingRouteImport } from './routes/_authenticated.dashboard.pricing'
import { Route as AuthenticatedDashboardPrinterRouteImport } from './routes/_authenticated.dashboard.printer'
import { Route as AuthenticatedDashboardQrRouteImport } from './routes/_authenticated.dashboard.qr'
import { Route as AuthenticatedDashboardSettingsRouteImport } from './routes/_authenticated.dashboard.settings'
import { Route as PrintJobJobIdRouteImport } from './routes/print.job.$jobId'
import { Route as PrintSessionTokenRouteImport } from './routes/print.session.$token'
import { Route as StationStationIdDisplayRouteImport } from './routes/station.$stationId.display'
import { Route as ApiPublicPrintAgentHeartbeatRouteImport } from './routes/api/public/print-agent/heartbeat'
import { Route as ApiPublicPrintAgentJobsRouteImport } from './routes/api/public/print-agent/jobs'
import { Route as ApiPublicPrintAgentJobsJobIdClaimRouteImport } from './routes/api/public/print-agent/jobs.$jobId.claim'
import { Route as ApiPublicPrintAgentJobsJobIdStatusRouteImport } from './routes/api/public/print-agent/jobs.$jobId.status'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardHistoryRoute =
  AuthenticatedDashboardHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardJobsRoute =
  AuthenticatedDashboardJobsRouteImport.update({
    id: '/jobs',
    path: '/jobs',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardPricingRoute =
  AuthenticatedDashboardPricingRouteImport.update({
    id: '/pricing',
    path: '/pricing',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardPrinterRoute =
  AuthenticatedDashboardPrinterRouteImport.update({
    id: '/printer',
    path: '/printer',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardQrRoute =
  AuthenticatedDashboardQrRouteImport.update({
    id: '/qr',
    path: '/qr',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSettingsRoute =
  AuthenticatedDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const PrintJobJobIdRoute = PrintJobJobIdRouteImport.update({
  id: '/print/job/$jobId',
  path: '/print/job/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintSessionTokenRoute = PrintSessionTokenRouteImport.update({
  id: '/print/session/$token',
  path: '/print/session/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const StationStationIdDisplayRoute = StationStationIdDisplayRouteImport.update({
  id: '/station/$stationId/display',
  path: '/station/$stationId/display',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPrintAgentHeartbeatRoute =
  ApiPublicPrintAgentHeartbeatRouteImport.update({
    id: '/api/public/print-agent/heartbeat',
    path: '/api/public/print-agent/heartbeat',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPrintAgentJobsRoute = ApiPublicPrintAgentJobsRouteImport.update({
  id: '/api/public/print-agent/jobs',
  path: '/api/public/print-agent/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPrintAgentJobsJobIdClaimRoute =
  ApiPublicPrintAgentJobsJobIdClaimRouteImport.update({
    id: '/$jobId/claim',
    path: '/$jobId/claim',
    getParentRoute: () => ApiPublicPrintAgentJobsRoute,
  } as any)
const ApiPublicPrintAgentJobsJobIdStatusRoute =
  ApiPublicPrintAgentJobsJobIdStatusRouteImport.update({
    id: '/$jobId/status',
    path: '/$jobId/status',
    getParentRoute: () => ApiPublicPrintAgentJobsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/dashboard/history': typeof AuthenticatedDashboardHistoryRoute
  '/dashboard/jobs': typeof AuthenticatedDashboardJobsRoute
  '/dashboard/pricing': typeof AuthenticatedDashboardPricingRoute
  '/dashboard/printer': typeof AuthenticatedDashboardPrinterRoute
  '/dashboard/qr': typeof AuthenticatedDashboardQrRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/print/job/$jobId': typeof PrintJobJobIdRoute
  '/print/session/$token': typeof PrintSessionTokenRoute
  '/station/$stationId/display': typeof StationStationIdDisplayRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/api/public/print-agent/heartbeat': typeof ApiPublicPrintAgentHeartbeatRoute
  '/api/public/print-agent/jobs': typeof ApiPublicPrintAgentJobsRouteWithChildren
  '/api/public/print-agent/jobs/$jobId/claim': typeof ApiPublicPrintAgentJobsJobIdClaimRoute
  '/api/public/print-agent/jobs/$jobId/status': typeof ApiPublicPrintAgentJobsJobIdStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/dashboard/history': typeof AuthenticatedDashboardHistoryRoute
  '/dashboard/jobs': typeof AuthenticatedDashboardJobsRoute
  '/dashboard/pricing': typeof AuthenticatedDashboardPricingRoute
  '/dashboard/printer': typeof AuthenticatedDashboardPrinterRoute
  '/dashboard/qr': typeof AuthenticatedDashboardQrRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/print/job/$jobId': typeof PrintJobJobIdRoute
  '/print/session/$token': typeof PrintSessionTokenRoute
  '/station/$stationId/display': typeof StationStationIdDisplayRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/api/public/print-agent/heartbeat': typeof ApiPublicPrintAgentHeartbeatRoute
  '/api/public/print-agent/jobs': typeof ApiPublicPrintAgentJobsRouteWithChildren
  '/api/public/print-agent/jobs/$jobId/claim': typeof ApiPublicPrintAgentJobsJobIdClaimRoute
  '/api/public/print-agent/jobs/$jobId/status': typeof ApiPublicPrintAgentJobsJobIdStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/dashboard/history': typeof AuthenticatedDashboardHistoryRoute
  '/_authenticated/dashboard/jobs': typeof AuthenticatedDashboardJobsRoute
  '/_authenticated/dashboard/pricing': typeof AuthenticatedDashboardPricingRoute
  '/_authenticated/dashboard/printer': typeof AuthenticatedDashboardPrinterRoute
  '/_authenticated/dashboard/qr': typeof AuthenticatedDashboardQrRoute
  '/_authenticated/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/print/job/$jobId': typeof PrintJobJobIdRoute
  '/print/session/$token': typeof PrintSessionTokenRoute
  '/station/$stationId/display': typeof StationStationIdDisplayRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/api/public/print-agent/heartbeat': typeof ApiPublicPrintAgentHeartbeatRoute
  '/api/public/print-agent/jobs': typeof ApiPublicPrintAgentJobsRouteWithChildren
  '/api/public/print-agent/jobs/$jobId/claim': typeof ApiPublicPrintAgentJobsJobIdClaimRoute
  '/api/public/print-agent/jobs/$jobId/status': typeof ApiPublicPrintAgentJobsJobIdStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/dashboard'
    | '/dashboard/history'
    | '/dashboard/jobs'
    | '/dashboard/pricing'
    | '/dashboard/printer'
    | '/dashboard/qr'
    | '/dashboard/settings'
    | '/print/job/$jobId'
    | '/print/session/$token'
    | '/station/$stationId/display'
    | '/dashboard/'
    | '/api/public/print-agent/heartbeat'
    | '/api/public/print-agent/jobs'
    | '/api/public/print-agent/jobs/$jobId/claim'
    | '/api/public/print-agent/jobs/$jobId/status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/dashboard/history'
    | '/dashboard/jobs'
    | '/dashboard/pricing'
    | '/dashboard/printer'
    | '/dashboard/qr'
    | '/dashboard/settings'
    | '/print/job/$jobId'
    | '/print/session/$token'
    | '/station/$stationId/display'
    | '/dashboard'
    | '/api/public/print-agent/heartbeat'
    | '/api/public/print-agent/jobs'
    | '/api/public/print-agent/jobs/$jobId/claim'
    | '/api/public/print-agent/jobs/$jobId/status'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/_authenticated/dashboard'
    | '/_authenticated/dashboard/history'
    | '/_authenticated/dashboard/jobs'
    | '/_authenticated/dashboard/pricing'
    | '/_authenticated/dashboard/printer'
    | '/_authenticated/dashboard/qr'
    | '/_authenticated/dashboard/settings'
    | '/print/job/$jobId'
    | '/print/session/$token'
    | '/station/$stationId/display'
    | '/_authenticated/dashboard/'
    | '/api/public/print-agent/heartbeat'
    | '/api/public/print-agent/jobs'
    | '/api/public/print-agent/jobs/$jobId/claim'
    | '/api/public/print-agent/jobs/$jobId/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  PrintJobJobIdRoute: typeof PrintJobJobIdRoute
  PrintSessionTokenRoute: typeof PrintSessionTokenRoute
  StationStationIdDisplayRoute: typeof StationStationIdDisplayRoute
  ApiPublicPrintAgentHeartbeatRoute: typeof ApiPublicPrintAgentHeartbeatRoute
  ApiPublicPrintAgentJobsRoute: typeof ApiPublicPrintAgentJobsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/history': {
      id: '/_authenticated/dashboard/history'
      path: '/history'
      fullPath: '/dashboard/history'
      preLoaderRoute: typeof AuthenticatedDashboardHistoryRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/jobs': {
      id: '/_authenticated/dashboard/jobs'
      path: '/jobs'
      fullPath: '/dashboard/jobs'
      preLoaderRoute: typeof AuthenticatedDashboardJobsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/pricing': {
      id: '/_authenticated/dashboard/pricing'
      path: '/pricing'
      fullPath: '/dashboard/pricing'
      preLoaderRoute: typeof AuthenticatedDashboardPricingRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/printer': {
      id: '/_authenticated/dashboard/printer'
      path: '/printer'
      fullPath: '/dashboard/printer'
      preLoaderRoute: typeof AuthenticatedDashboardPrinterRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/qr': {
      id: '/_authenticated/dashboard/qr'
      path: '/qr'
      fullPath: '/dashboard/qr'
      preLoaderRoute: typeof AuthenticatedDashboardQrRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/settings': {
      id: '/_authenticated/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/print/job/$jobId': {
      id: '/print/job/$jobId'
      path: '/print/job/$jobId'
      fullPath: '/print/job/$jobId'
      preLoaderRoute: typeof PrintJobJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/session/$token': {
      id: '/print/session/$token'
      path: '/print/session/$token'
      fullPath: '/print/session/$token'
      preLoaderRoute: typeof PrintSessionTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/station/$stationId/display': {
      id: '/station/$stationId/display'
      path: '/station/$stationId/display'
      fullPath: '/station/$stationId/display'
      preLoaderRoute: typeof StationStationIdDisplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/print-agent/heartbeat': {
      id: '/api/public/print-agent/heartbeat'
      path: '/api/public/print-agent/heartbeat'
      fullPath: '/api/public/print-agent/heartbeat'
      preLoaderRoute: typeof ApiPublicPrintAgentHeartbeatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/print-agent/jobs': {
      id: '/api/public/print-agent/jobs'
      path: '/api/public/print-agent/jobs'
      fullPath: '/api/public/print-agent/jobs'
      preLoaderRoute: typeof ApiPublicPrintAgentJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/print-agent/jobs/$jobId/claim': {
      id: '/api/public/print-agent/jobs/$jobId/claim'
      path: '/$jobId/claim'
      fullPath: '/api/public/print-agent/jobs/$jobId/claim'
      preLoaderRoute: typeof ApiPublicPrintAgentJobsJobIdClaimRouteImport
      parentRoute: typeof ApiPublicPrintAgentJobsRoute
    }
    '/api/public/print-agent/jobs/$jobId/status': {
      id: '/api/public/print-agent/jobs/$jobId/status'
      path: '/$jobId/status'
      fullPath: '/api/public/print-agent/jobs/$jobId/status'
      preLoaderRoute: typeof ApiPublicPrintAgentJobsJobIdStatusRouteImport
      parentRoute: typeof ApiPublicPrintAgentJobsRoute
    }
  }
}

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardHistoryRoute: typeof AuthenticatedDashboardHistoryRoute
  AuthenticatedDashboardJobsRoute: typeof AuthenticatedDashboardJobsRoute
  AuthenticatedDashboardPricingRoute: typeof AuthenticatedDashboardPricingRoute
  AuthenticatedDashboardPrinterRoute: typeof AuthenticatedDashboardPrinterRoute
  AuthenticatedDashboardQrRoute: typeof AuthenticatedDashboardQrRoute
  AuthenticatedDashboardSettingsRoute: typeof AuthenticatedDashboardSettingsRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardHistoryRoute: AuthenticatedDashboardHistoryRoute,
    AuthenticatedDashboardJobsRoute: AuthenticatedDashboardJobsRoute,
    AuthenticatedDashboardPricingRoute: AuthenticatedDashboardPricingRoute,
    AuthenticatedDashboardPrinterRoute: AuthenticatedDashboardPrinterRoute,
    AuthenticatedDashboardQrRoute: AuthenticatedDashboardQrRoute,
    AuthenticatedDashboardSettingsRoute: AuthenticatedDashboardSettingsRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ApiPublicPrintAgentJobsRouteChildren {
  ApiPublicPrintAgentJobsJobIdClaimRoute: typeof ApiPublicPrintAgentJobsJobIdClaimRoute
  ApiPublicPrintAgentJobsJobIdStatusRoute: typeof ApiPublicPrintAgentJobsJobIdStatusRoute
}

const ApiPublicPrintAgentJobsRouteChildren: ApiPublicPrintAgentJobsRouteChildren =
  {
    ApiPublicPrintAgentJobsJobIdClaimRoute:
      ApiPublicPrintAgentJobsJobIdClaimRoute,
    ApiPublicPrintAgentJobsJobIdStatusRoute:
      ApiPublicPrintAgentJobsJobIdStatusRoute,
  }

const ApiPublicPrintAgentJobsRouteWithChildren =
  ApiPublicPrintAgentJobsRoute._addFileChildren(
    ApiPublicPrintAgentJobsRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  PrintJobJobIdRoute: PrintJobJobIdRoute,
  PrintSessionTokenRoute: PrintSessionTokenRoute,
  StationStationIdDisplayRoute: StationStationIdDisplayRoute,
  ApiPublicPrintAgentHeartbeatRoute: ApiPublicPrintAgentHeartbeatRoute,
  ApiPublicPrintAgentJobsRoute: ApiPublicPrintAgentJobsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
